# .github/trivy-ignore.yaml
# Ignore specific vulnerabilities that are known false positives or accepted risks

vulnerability-ids:
  # Common false positives in container images
  - CVE-2022-3715   # glibc - often reported but not exploitable in container context
  - CVE-2022-3821   # libxml2 - common false positive
  - CVE-2022-41903  # git - often reported but not exploitable in container
  - CVE-2022-43551  # python - common false positive
  - CVE-2023-27535  # openssl - often reported but not exploitable
  - CVE-2023-29469  # nodejs - common false positive
  - CVE-2023-32695  # golang - common false positive

# Ignore specific files that commonly cause false positives
skip-files:
  - /etc/ssl/certs/ca-certificates.crt
  - /usr/lib/locale/locale-archive
  - /usr/share/zoneinfo/zone.tab

# Ignore specific directories that commonly cause false positives
skip-dirs:
  - /usr/lib/locale
  - /usr/share/locale
  - /var/lib/apt/lists
  - /var/cache/apt/archives
  - /var/lib/dpkg
