extends: default

rules:
  line-length:
    max: 150
    level: warning
  comments-indentation: disable
  comments: disable
  empty-lines:
    max-start: 3
    max-end: 2
    max: 3
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  trailing-spaces: enable
