extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments-indentation: disable
  comments: disable
  empty-lines:
    max-start: 2
    max-end: 1
    max: 2
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
