services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole-server
    networks:
      pihole_net:
        ipv4_address: 172.20.0.3
      isolated_net:  # Block outbound DNS
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/logs:/var/log/pihole
    environment:
      TZ: ${TZ:-Australia/Sydney}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      DNS1: 172.20.0.2#5053  # Unbound
      DNS2: 127.0.0.1#5053   # Fallback to Unbound
      VIRTUAL_HOST: pihole.local
      VIRTUAL_PORT: 80
      ServerIP: ${PI_STATIC_IP:-192.168.1.XXX}
      PIHOLE_DNS_: 172.20.0.2#5053
      PIHOLE_INTERFACE: eth0
      FTLCONF_LOCAL_IPV4: 172.20.0.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin/api.php?summary"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    dns:
      - 172.20.0.2
      - 127.0.0.1

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound-server
    networks:
      pihole_net:
        ipv4_address: 172.20.0.2
    volumes:
      - ./unbound/config:/etc/unbound/custom
      - ./unbound/logs:/var/log/unbound
    environment:
      TZ: ${TZ:-Australia/Sydney}
    ports:
      - "127.0.0.1:5053:5053/tcp"
      - "127.0.0.1:5053:5053/udp"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "unbound-control", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: -d -v

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    internal: false
  isolated_net:
    driver: bridge
    internal: true

