version: '3.8'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    hostname: homeassistant-server
    network_mode: host # Crucial for local device discovery
    networks:
      - smart_home_net
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ:-Australia/Sydney}
      PUID: 1000
      PGID: 1000
    ports:
      - "8123:8123"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Z-Wave/Zigbee dongle
      - /dev/ttyACM0:/dev/ttyACM0  # Alternative USB device

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea-server
    networks:
      - dev_net
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ:-Australia/Sydney}
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__server__DOMAIN: gitea.local
      GITEA__server__ROOT_URL: http://gitea.local:3000
      GITEA__server__SSH_DOMAIN: gitea.local
      GITEA__server__SSH_PORT: 2222
      GITEA__server__HTTP_PORT: 3000
      GITEA__server__PROTOCOL: http
      GITEA__security__INSTALL_LOCK: true
      GITEA__service__DISABLE_REGISTRATION: false
      GITEA__service__REQUIRE_SIGNIN_VIEW: false
      GITEA__log__LEVEL: Info
      GITEA__log__ROOT_PATH: /data/gitea/log
    ports:
      - "3002:3000"
      - "2222:22"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer-server
    networks:
      - management_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    environment:
      TZ: ${TZ:-Australia/Sydney}
    ports:
      - "9000:9000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle-server
    networks:
      - management_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ:-Australia/Sydney}
    ports:
      - "8080:8080" # Dozzle web interface
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  speedtest-tracker:
    image: henrywhitaker3/speedtest-tracker:latest
    container_name: speedtest-tracker
    hostname: speedtest-tracker-server
    networks:
      - management_net
    volumes:
      - speedtest_data:/config
    environment:
      TZ: ${TZ:-Australia/Sydney}
      PUID: 1000
      PGID: 1000
      OOKLA_EULA_GDPR: "true" # Accept Ookla EULA
    ports:
      - "8787:80" # Speedtest Tracker web interface
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower-server
    networks:
      - management_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ:-Australia/Sydney}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${WATCHTOWER_EMAIL_FROM:-noreply@yourdomain.local}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${WATCHTOWER_EMAIL_TO:-admin@yourdomain.local}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${WATCHTOWER_EMAIL_SERVER:-smtp.gmail.com}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: ${WATCHTOWER_EMAIL_PORT:-587}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${WATCHTOWER_EMAIL_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${WATCHTOWER_EMAIL_PASSWORD}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          memory: 64M

volumes:
  homeassistant_data:
    driver: local
  gitea_data:
    driver: local
  portainer_data:
    driver: local
  speedtest_data:
    driver: local

networks:
  smart_home_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
  dev_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
  management_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1


